socket.o: socket.c socket.h signaux.h analyzer.h answer.h
signaux.o: signaux.c signaux.h analyzer.h answer.h
answer.o: answer.c answer.h analyzer.h
main.o: main.c socket.h signaux.h analyzer.h answer.h
analyzer.o: analyzer.c analyzer.h
